const navs=document.querySelectorAll(".nav");function showSection(id){document.querySelectorAll(".section").forEach(s=>s.classList.remove("active"));document.getElementById(id).classList.add("active");navs.forEach(n=>n.classList.toggle("active",n.dataset.section===id));document.getElementById("pageTitle").textContent=id==="dashboard"?"Good Morning, Jyoti Gruh Udhyog":({poster:"AI Poster Generator",calendar:"Occasion & Daily Calendar",reviews:"Review Marketing",publishing:"Social Publishing",analytics:"Marketing Analytics"}[id]||"Jyoti AI Marketing")}navs.forEach(n=>n.onclick=()=>showSection(n.dataset.section));

const canvas=document.getElementById("posterCanvas"),ctx=canvas.getContext("2d");let uploaded=null;
document.getElementById("photo").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const img=new Image();img.onload=()=>{uploaded=img;generatePoster()};img.src=URL.createObjectURL(f)});
function fitImage(img,x,y,w,h){const r=Math.max(w/img.width,h/img.height),nw=img.width*r,nh=img.height*r;ctx.drawImage(img,x+(w-nw)/2,y+(h-nh)/2,nw,nh)}
function generatePoster(){const name=document.getElementById("productName").value||"Jyoti Special";const wt=document.getElementById("weight").value||"";const price=document.getElementById("price").value||"";const occ=document.getElementById("occasion").value;const tag=document.getElementById("tagline").value||"";ctx.clearRect(0,0,1080,1080);ctx.fillStyle="#f5ecd8";ctx.fillRect(0,0,1080,1080);ctx.fillStyle="#123d2b";ctx.fillRect(0,0,1080,170);ctx.fillStyle="#d7ae43";ctx.font="bold 34px Arial";ctx.fillText("🪔 JYOTI GRUH UDHYOG",60,75);ctx.fillStyle="#fff";ctx.font="24px Arial";ctx.fillText("RAJKOT",62,120);if(uploaded){fitImage(uploaded,90,220,900,500)}else{ctx.fillStyle="#e5dcc8";ctx.fillRect(90,220,900,500);ctx.fillStyle="#876f43";ctx.font="bold 42px Arial";ctx.textAlign="center";ctx.fillText("PRODUCT PHOTO",540,480);ctx.textAlign="left")}if(occ){ctx.fillStyle="#d7ae43";ctx.fillRect(90,750,900,55);ctx.fillStyle="#173c2a";ctx.font="bold 25px Arial";ctx.textAlign="center";ctx.fillText(occ.toUpperCase(),540,787);ctx.textAlign="left"}ctx.fillStyle="#123d2b";ctx.font="bold 55px Arial";ctx.textAlign="center";ctx.fillText(name,540,870);ctx.font="26px Arial";ctx.fillText(tag,540,915);ctx.font="bold 38px Arial";ctx.fillText(`${wt}   •   ${price}`,540,970);ctx.font="22px Arial";ctx.fillText("Fresh • Premium • Homemade Taste",540,1020);ctx.textAlign="left"}
function downloadPoster(){const a=document.createElement("a");a.download=(document.getElementById("productName").value||"jyoti-poster").replace(/\s+/g,"-")+".png";a.href=canvas.toDataURL("image/png");a.click()}
generatePoster();

const occasions=["Aug 15 — Independence Day","Aug 16 — Daily Product","Aug 26 — Janmashtami","Sep 4 — Ganesh Chaturthi","Sep 15 — Navratri preparation","Oct 20 — Diwali preparation"];document.getElementById("calendarList").innerHTML=occasions.map(x=>`<div class="plan"><b>${x.split(" — ")[0]}</b><span>${x.split(" — ")[1]}</span></div>`).join("");
